{% set name = "rdata" %}
{% set version = "0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rdata-{{ version }}.tar.gz
  sha256: 5e2c61aad1366be8c4363a0ae58fbcf6ec894dc1b861e80af713c0c38d1887ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - numpy
    - pandas
    - python >=3.6,<4.0
    - xarray

test:
  imports:
    - rdata
    - rdata.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vnmabus/rdata
  summary: 'rdata: read R datasets from Python.'
  license: MIT
  license_file: LICENSE
  description: |
    This package parses .rda datasets used in R. It does not depend on the R
    language or its libraries, and thus it is released under a MIT license.
  doc_url: https://rdata.readthedocs.io/
  dev_url: https://github.com/vnmabus/rdata

extra:
  recipe-maintainers:
    - vnmabus
